# Generated by Django 5.0.2 on 2024-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='product_images')),
                ('category', models.CharField(choices=[('smart phone', 'smart phone'), ('tablets', 'tablets'), ('smart watches', 'smart watches'), ('laptops', 'laptops')], max_length=200)),
            ],
        ),
    ]
