# Generated by Django 5.0.2 on 2024-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('order placed', 'order placed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='order placed', max_length=200),
        ),
    ]
